feature/1584 - Add airport file, entry to airportLoadList.js
openscope/openscope pull request #1585
Opened 2020-05-18 04:03 UTC by JPmAn24

Resolves #1584 

The purpose of this pull request is to add PHNL - Daniel K Inouye International Airport

2021-12-13 22:42 UTC, MichaelDMcCracken commented
Does anyone care if I revive this?

2022-01-31 04:10 UTC, MichaelDMcCracken commented
@erikquinn @Fechulo 

Can someone update this branch to 6.26.0 or 6.27.0? I'm keep screwing it up when I try to do it locally.

2022-02-03 13:16 UTC, Fechulo requested changes
Missing fix definitions
![image](https://user-images.githubusercontent.com/13125311/152349777-32a4047f-dbd7-4c44-87ec-130b1cb03416.png)

If you have the time and energy, it'd be nice to modify the terrain to match the video map. This is fairly straight forward to do using qGIS with tracing on

2022-02-03 13:16 UTC, Fechulo commented on assets/airports/phnl.json
> +                "CHAIN": ["CHAIN", "SOBOW", "SERAH"],
The 13DME arc returns!

2022-02-03 13:16 UTC, Fechulo commented on assets/airports/phnl.json
> +            "entryPoints": {
Missing LNY transition

2022-02-04 03:34 UTC, MichaelDMcCracken commented on assets/airports/phnl.json
> +                "NONNI": ["NONNI"],
- [x]

2022-02-04 05:25 UTC, MichaelDMcCracken commented on assets/airports/phnl.json
> +                "CHAIN": ["CHAIN", "SOBOW", "SERAH", "SAKKI"],
I was being lazy.... but I have added this nonetheless

2022-02-04 05:26 UTC, MichaelDMcCracken commented
@Fechulo 
Requested changes have been pushed.

2022-02-04 11:27 UTC, Fechulo approved these changes

2022-02-21 18:20 UTC, erikquinn requested changes
@MichaelDMcCracken Applied this PR to the latest version of the sim, and there are some issues with the formatting of certain sections that are causing issues. Just need to address those so it works with the latest version 🙂

2022-02-22 16:14 UTC, MichaelDMcCracken commented
> @MichaelDMcCracken Applied this PR to the latest version of the sim, and there are some issues with the formatting of certain sections that are causing issues. Just need to address those so it works with the latest version 🙂

So I updated this locally (the restricted areas need to be defined as "poly" instead of "coordinates"), but totally goobered things up with git. Might be easier if you make the edit yourself, because my local branch is toast ...

<img width="682" alt="image" src="https://user-images.githubusercontent.com/26231967/155172944-19086088-6834-4fc3-9814-6b9af6644381.png">

2022-02-22 19:47 UTC, erikquinn commented
It's an easy fix. I sent you a message on slack :)

2022-03-18 20:26 UTC, merged