Add Contour Airlines (VTE)
openscope/openscope pull request #1757
Opened 2021-02-06 20:46 UTC by Hawaiicoder

Resolves #1756 

The purpose of this pull request is to add Contour Airlines for the KBWI airport project.

2021-02-08 16:28 UTC, erikquinn submitted a review, later dismissed
Please use @openscope/airport-reviewers for all PRs on any changes that only involve airport/airline changes.

2021-02-08 16:28 UTC, erikquinn commented on assets/airlines/vte.json
> +}
always need an empty line at the end of the file.

2021-02-08 17:45 UTC, Fechulo requested changes
Looks like they might have more than just Embraers:

> The company operates a diverse fleet of aircraft for private charter, ranging in size from 8 passenger light jets to three cabin ultra long-range business jets.

Taken from their [website](https://contourairlines.com/corporate/about-us)

According to [FlightRadar24](https://www.flightradar24.com/data/airlines/lf-vte/fleet) they have a few others as well

2021-02-09 01:24 UTC, Hawaiicoder commented
@erikquinn Understood on both- thanks for letting me know. 
@Fechulo Data was taken from Planespotters but I will be updating according to the FR24 data.

2021-02-10 09:57 UTC, Fechulo approved these changes

2021-02-11 18:02 UTC, Hawaiicoder commented
Is there anything else I need to do for this to be merged?

2021-02-11 18:13 UTC, erikquinn commented
no, it just takes time. they have to go in one at a time, and this one was not at the top of the priority list. once you get an approved review, it will only be a matter of time, and it should not be adjusted any further unless coordinated otherwise.

2021-02-11 18:14 UTC, merged

2021-02-11 18:28 UTC, Hawaiicoder commented
Good to know! Thanks!