feature/1405 - Implement automatic departures
openscope/openscope pull request #1824
Opened 2021-05-29 02:55 UTC by erikquinn

Resolves #1405.

2021-05-29 04:24 UTC, n8rzz approved these changes

2021-05-29 04:24 UTC, n8rzz commented on src/assets/scripts/client/aircraft/AircraftConflict.js
>          // Ignore aircraft in the first minute of their flight
is this comment still valid?

2021-05-29 09:45 UTC, Fechulo requested changes
LOVE IT! :shipit: 

Couple of things I noticed though:

- A few departures spawned in with landing aircraft on the runway, resulting in:
![image](https://user-images.githubusercontent.com/13125311/120065429-26346880-c069-11eb-9414-65a9e5b341a9.png)

- Increasing the departure rate results in a few radar contact losses...
![image](https://user-images.githubusercontent.com/13125311/120065504-82978800-c069-11eb-9f12-c23b69f0100d.png)
- The conflict detection doesn't seem to be doing great (KLAX, normal rate)
![image](https://user-images.githubusercontent.com/13125311/120065594-fb96df80-c069-11eb-8086-00eface9342f.png)

- Questionable decisions with crossing runways:
![image](https://user-images.githubusercontent.com/13125311/120065630-36991300-c06a-11eb-9999-9c9aa99f5df0.png)
![image](https://user-images.githubusercontent.com/13125311/120065640-43b60200-c06a-11eb-8a53-f9fc726a58e1.png)

I'll keep playing with it and see if I find anything else, but I'm very excited to have this in the sim 😄

2021-06-02 19:20 UTC, erikquinn commented
@Fechulo yep! the first I was actually able to fix (thought it'd be too hard, but a quick solution was actually not too bad).

The second one is kinda the best we can do atm I think-- I increased the invincibility period from 60 seconds from starting takeoff roll to 90 seconds-- that's the slight delay you're seeing. Can be reduced if you think that's appropriate. It's just hard to get the tower to space them on their own.

Regarding crossing runways, that will need to be an enhancement to this feature. Just can't get something like that done rn. Will label the option appropriately so it's clear that this is an experimental feature. :)

2021-06-02 20:28 UTC, merged