feature/1920 — Add Salt Lake City Int'l (SLC)
openscope/openscope pull request #1921
Opened 2022-02-20 20:02 UTC by MichaelDMcCracken

Resolves #1920

The purpose of this pull request is to add SLC.

2022-05-24 19:06 UTC, Fechulo requested changes
Sorry for the long wait, a few small changes needed

2022-05-24 19:06 UTC, Fechulo commented on assets/airports/kslc.json
> +    "stars": {
Missing Brigham City Four (LHO4) Arrival

2022-05-24 19:06 UTC, Fechulo commented on assets/airports/airportLoadList.json
> +        "level": "hard",
With 53.6acph, this should be medium

2022-05-25 19:23 UTC, MichaelDMcCracken commented on assets/airports/kslc.json
> +    "airspace": [
The ZLC VATSIM documentation I had was very generic, didn't have a full-on airspace detail like some other ARTCCs.

2022-05-25 19:30 UTC, MichaelDMcCracken commented on assets/airports/kslc.json
> +    "stars": {
fixed

2022-05-25 19:30 UTC, MichaelDMcCracken commented on assets/airports/kslc.json
> +                "BCE": ["BCE", "SLINA", "DTA"],
no idea why I did that, fixed.

2022-05-25 19:32 UTC, MichaelDMcCracken commented on assets/airports/kslc.json
> +            "body": [["CORVR", "A130+"], ["CGULL", "A150+"], "MOFER", "SCOVL", "DRYAD", "TWF"],
FIXED

2022-05-25 21:57 UTC, Fechulo commented on assets/airports/kslc.json
> +    "airspace": [
Yeah I couldn't find much of anything

2022-05-25 21:58 UTC, Fechulo approved these changes

2022-07-03 15:42 UTC, merged