Feature/1952 - Update MCO to AIRAC 2205
openscope/openscope pull request #1953
Opened 2022-06-04 04:01 UTC by MichaelDMcCracken

Resolves #1952 
The purpose of this pull request is to update MCO to AIRAC 2205.

2022-06-05 22:12 UTC, Fechulo requested changes

2022-06-05 22:12 UTC, Fechulo commented on assets/airports/kmco.json
>              "name": "Mizulo Two",
Three

2022-06-05 22:12 UTC, Fechulo commented on assets/airports/kmco.json
> +            "icao": "RDSOX1",
OSPRY1

2022-06-05 22:12 UTC, Fechulo commented on assets/airports/kmco.json
> +            "name": "Red Sox Two",
One

2022-06-06 15:21 UTC, MichaelDMcCracken commented on assets/airports/kmco.json
> +            "icao": "RDSOX1",
fixed

2022-06-06 18:46 UTC, Fechulo approved these changes

2022-07-03 17:20 UTC, merged